CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  has_avatar INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  author_id TEXT NOT NULL,
  timestamp INTEGER NOT NULL,
  caption TEXT NOT NULL DEFAULT "",
  media_type TEXT,
  reactions INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (author_id) REFERENCES users(id)
);
