CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  timestamp INTEGER NOT NULL,
  caption TEXT,
  media_type TEXT,
  reactions INTEGER DEFAULT 0,
  FOREIGN KEY (author_id) REFERENCES users(id)
);
